name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Build the Docker image
      run: docker build --tag lavalink:${GITHUB_REF##*/} .
